# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Lemniscate
tagline:          'Random Ramblings'
description:      'UA <a href="http://uaftab.com" target="_blank">Website</a>'
url:              http://uaftab.com
baseurl:          /

author:
  name:           'Umair Aftab'
  url:            https://uaftab.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/uaftab
