# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Lemniscate
tagline:          'UA'
description:      '<a href="http://uaftab.com" target="_blank">UA</a>'
url:              http://uaftab.github.io
baseurl:          /

author:
  name:           'Umair Aftab'
  url:            http://uaftab.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/uaftab
